[files]
extend-exclude = [
    "website/client/.vitepress/config/*.ts",
    "website/client/src/**/*.md",
    ".git",
]
ignore-hidden = false

[default.extend-words]
# Vietnamese language words that might be flagged as typos
Nam = "Nam"  # Part of "Việt Nam" (Vietnam in Vietnamese)
