[files]
extend-exclude = [
    "website/client/.vitepress/config/*.ts",
    "website/client/src/**/*.md",
    ".git",
    "browser/**/*.txt",
]
ignore-hidden = false

default.extend-ignore-re = [
    "Việt Nam",
]
